module.exports = {
  'PENDING': 'PENDING',
  'ERROR': 'ERROR',

  'LOAD_WHISKIES': 'LOAD_WHISKIES',
  'RECEIVE_WHISKIES': 'RECEIVE_WHISKIES',
  'LOAD_WHISKY': 'LOAD_WHISKY',
  'RECEIVE_WHISKY': 'RECEIVE_WHISKY',
  'CREATE_WHISKY': 'CREATE_WHISKY',
  'RECEIVE_CREATED_WHISKY': 'RECEIVE_CREATED_WHISKY'
};
